import {
  FaPython,
  FaServer,
  FaJava,
  FaLeaf,
  FaCode,
  FaDocker,
  FaGlobe,
  FaCloud,
  FaUserGraduate,
  FaCertificate,
  FaNetworkWired,
  FaWhatsapp,
  FaLinkedinIn,
  FaFacebookF,
  FaEnvelope,
  FaPhoneAlt,
  FaDownload,
  FaArrowRight,
  FaExternalLinkAlt,
  FaExpand,
  FaMapMarkerAlt,
  FaHeart,
  FaArrowUp,
  FaGithub,
  FaUserAstronaut,
  FaRocket,
  FaBrain,
  FaCheck,
} from 'react-icons/fa'

const registry = {
  python: FaPython,
  server: FaServer,
  java: FaJava,
  leaf: FaLeaf,
  code: FaCode,
  docker: FaDocker,
  globe: FaGlobe,
  cloud: FaCloud,
  graduate: FaUserGraduate,
  certificate: FaCertificate,
  network: FaNetworkWired,
  whatsapp: FaWhatsapp,
  linkedin: FaLinkedinIn,
  facebook: FaFacebookF,
  mail: FaEnvelope,
  phone: FaPhoneAlt,
  download: FaDownload,
  arrowRight: FaArrowRight,
  external: FaExternalLinkAlt,
  expand: FaExpand,
  pin: FaMapMarkerAlt,
  heart: FaHeart,
  arrowUp: FaArrowUp,
  github: FaGithub,
  who: FaUserAstronaut,
  mission: FaRocket,
  approach: FaBrain,
  check: FaCheck,
}

export default function Icon({ name, className, ...rest }) {
  const Glyph = registry[name]
  if (!Glyph) return null
  return <Glyph className={className} aria-hidden="true" focusable="false" {...rest} />
}
